services:
  mysql:
    image: mysql:8.0
    container_name: table-definition-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: test_database
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpassword
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      timeout: 20s
      retries: 10

  postgresql:
    image: postgres:15
    container_name: table-definition-postgresql
    environment:
      POSTGRES_DB: test_database
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpassword
    ports:
      - '5432:5432'
    volumes:
      - postgresql_data:/var/lib/postgresql/data
      - ./docker/postgresql/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U testuser -d test_database']
      timeout: 20s
      retries: 10

volumes:
  mysql_data:
  postgresql_data:
